apiVersion: v1
kind: Service
metadata:
  name: defect-detection-grafana
  labels:
    app: defect-detection-grafana
spec:
  type: NodePort
  selector:
    app: defect-detection-grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
