apiVersion: v1
kind: Service
metadata:
  name: defect-detection-prometheus
  labels:
    app: defect-detection-prometheus
spec:
  type: NodePort
  selector:
    app: defect-detection-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
