apiVersion: v1
kind: ConfigMap
metadata:
  name: defect-detection-prometheus-config
  labels:
    app: defect-detection-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "defect-detection-api"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["defect-detection-api:8000"]
