apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defect-detection-api-storage
  labels:
    app: defect-detection-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
